export { UsuarioService } from './componentes/usuario.service';
export { UserxsService } from './componentes/userxs.service';
export { UnidadService } from './componentes/unidad.service';
export { PersonaService } from './componentes/persona.service';
export { DatoPolicialService } from './componentes/dato-policial.service';
export { ArchivoService } from './componentes/archivo.service';
export { TematicaService } from './componentes/tematica.service';
export { UsuarioCivilService } from './componentes/usuario-civil.service';
export { SexoService } from './componentes/sexo.service';
export { RegistroUsuarioService} from './componentes/registro-usuario.service';
export {UsuariosOciService} from './componentes/usuarios-oci.service';
